
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '#Cy~\xb4}\xdc\xcd\xe3C\xde\xbd\rM3L'
    
_lr_action_items = {'CHAR':([2,6,8,10,11,12,13,14,16,17,18,20,21,22,23,],[-11,14,-14,-17,-15,14,-16,-12,-13,-8,-11,-9,-7,-10,14,]),'DPREC':([2,6,8,10,11,13,14,16,17,18,20,21,22,23,],[-11,9,-14,-17,-15,-16,-12,-13,-8,-11,-9,-7,-10,9,]),'STRING':([2,6,8,10,11,12,13,14,16,17,18,20,21,22,23,],[-11,10,-14,-17,-15,10,-16,-12,-13,-8,-11,-9,-7,-10,10,]),'INT':([9,],[20,]),'PREC':([2,6,8,10,11,13,14,16,17,18,20,21,22,23,],[-11,12,-14,-17,-15,-16,-12,-13,-8,-11,-9,-7,-10,12,]),'PIPE':([2,6,7,8,10,11,13,14,16,17,18,19,20,21,22,23,],[-11,-6,18,-14,-17,-15,-16,-12,-13,-8,-11,-5,-9,-7,-10,-4,]),'MERGE':([2,6,8,10,11,13,14,16,17,18,20,21,22,23,],[-11,15,-14,-17,-15,-16,-12,-13,-8,-11,-9,-7,-10,15,]),'COLON':([4,],[8,]),'SCOLON':([2,6,7,8,10,11,13,14,16,17,18,19,20,21,22,23,],[-11,-6,19,-14,-17,-15,-16,-12,-13,-8,-11,-5,-9,-7,-10,-4,]),'TYPE':([15,],[22,]),'ID':([0,1,2,3,5,6,7,8,10,11,12,13,14,16,17,18,19,20,21,22,23,],[4,4,-11,-1,-2,16,-3,-14,-17,-15,16,-16,-12,-13,-8,-11,-5,-9,-7,-10,16,]),'$end':([1,2,3,5,6,7,8,10,11,13,14,16,17,18,19,20,21,22,23,],[0,-11,-1,-2,-6,-3,-14,-17,-15,-16,-12,-13,-8,-11,-5,-9,-7,-10,-4,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'grammar':([0,],[1,]),'string_as_id':([6,12,23,],[11,11,11,]),'id_colon':([0,1,],[2,2,]),'rules':([0,1,],[3,5,]),'symbol':([6,12,23,],[17,21,17,]),'id':([6,12,23,],[13,13,13,]),'rhses_1':([2,],[7,]),'rhs':([2,18,],[6,23,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> grammar","S'",1,None,None,None),
  ('grammar -> rules','grammar',1,'p_grammer','/home/vinit/Website_here/code.py',85),
  ('grammar -> grammar rules','grammar',2,'p_grammer','/home/vinit/Website_here/code.py',86),
  ('rules -> id_colon rhses_1','rules',2,'p_rules','/home/vinit/Website_here/code.py',89),
  ('rhses_1 -> rhses_1 PIPE rhs','rhses_1',3,'p_rhses_1_pipe','/home/vinit/Website_here/code.py',109),
  ('rhses_1 -> rhses_1 SCOLON','rhses_1',2,'p_rhses_1_scolon','/home/vinit/Website_here/code.py',121),
  ('rhses_1 -> rhs','rhses_1',1,'p_rhses_1','/home/vinit/Website_here/code.py',125),
  ('rhs -> rhs PREC symbol','rhs',3,'p_rhs_prec','/home/vinit/Website_here/code.py',131),
  ('rhs -> rhs symbol','rhs',2,'p_rhs','/home/vinit/Website_here/code.py',137),
  ('rhs -> rhs DPREC INT','rhs',3,'p_rhs_drec','/home/vinit/Website_here/code.py',154),
  ('rhs -> rhs MERGE TYPE','rhs',3,'p_rhs_merge','/home/vinit/Website_here/code.py',160),
  ('rhs -> <empty>','rhs',0,'p_rhs_null','/home/vinit/Website_here/code.py',166),
  ('id -> CHAR','id',1,'p_id_char','/home/vinit/Website_here/code.py',170),
  ('id -> ID','id',1,'p_id','/home/vinit/Website_here/code.py',174),
  ('id_colon -> ID COLON','id_colon',2,'p_id_colon','/home/vinit/Website_here/code.py',178),
  ('symbol -> string_as_id','symbol',1,'p_symbol','/home/vinit/Website_here/code.py',185),
  ('symbol -> id','symbol',1,'p_symbol_id','/home/vinit/Website_here/code.py',193),
  ('string_as_id -> STRING','string_as_id',1,'p_string_as_id','/home/vinit/Website_here/code.py',201),
]
